### ISSUE TITLE
Seems to work somewhat but isn't downloading any chapters

### ISSUE THREAD

**Issue by MegaMagicPower** [SolRacht/WritingComDownloader#1]
Whenever I run the scrape command, it seems to work but always returns a "Chapters: 0" output, and rendering only renders a page with the story title and nothing else. I'm not sure what's going wrong. I have the latest JDK and Scala versions installed; is there a recommended one I maybe need to downgrade to?

Sometimes I also randomly get the exception "Failed all paths during title" which seems to resolve if I log out and back into the website and input the new cookie values, which makes me think in both cases there's some sort of connection problem going on. The conf instructions seemed straightforward except for the "user_token" part. In my cookie its called "user_ntoken". That's what you meant right?

Thanks for any help you can provide.

**Comment by SolRacht** [comment]
Did you set up the database?
I'm using `openjdk 11.0.2 2019-01-15`. SBT should be downloading the correct Scala version for you.

As for `user_ntoken`, it looks like this cookie was recently changed? It's now a very long hexy-looking string. How strange. I was having the same problem as you, but updating the token fixes it. I'm gonna push my changes soon, All you'll need to do is supply the new cookie values.

Let me know if the latest version solves your problem.

**Comment by MegaMagicPower** [comment]
It now traverses each chapter on the outline page (whereas before it would stop on the title), but each chapter now just outputs "Failed all paths during body". This is after recloning the repo and reinstalling everything with openjdk 11.0.2 and making sure to create the database as instructed on the main page. I'll try debugging it later and see if I can find something; I don't want to take up your time if its something stupid on my end. It looks from the instructions you made this on a Unix like system, whereas I'm on Windows. All of this is supposed to be portable but who knows.

E:\WritingComDownloader>sbt "run scrape"
OpenJDK 64-Bit Server VM warning: Ignoring option MaxPermSize; support was removed in 8.0
OpenJDK 64-Bit Server VM warning: Ignoring option MaxPermSize; support was removed in 8.0
[info] Loading project definition from E:\WritingComDownloader\project
[info] Loading settings for project writingcomdownloader from build.sbt ...
[info] Set current project to scraper (in build file:/E:/WritingComDownloader/)
[info] Packaging E:\WritingComDownloader\target\scala-2.13\scraper_2.13-0.1.0-SNAPSHOT.jar ...
[info] Done packaging.
[info] Running (fork) scraper.Main scrape
[info] Your coffee today: Cafe Au Lait
[info] 1 stories to check.
[info] [Pass the Write-Baton]: 984 new chapter(s).
[info] FAILED! https://writing.com/main/interact/item_id/Pass the Write-Baton/1 reason: Failed all paths during body
[info] FAILED! https://writing.com/main/interact/item_id/Pass the Write-Baton/11111 reason: Failed all paths during body
[info] FAILED! https://writing.com/main/interact/item_id/Pass the Write-Baton/11 reason: Failed all paths during body
[info] FAILED! https://writing.com/main/interact/item_id/Pass the Write-Baton/111 reason: Failed all paths during body
[info] FAILED! https://writing.com/main/interact/item_id/Pass the Write-Baton/1111 reason: Failed all paths during body
[info] FAILED! https://writing.com/main/interact/item_id/Pass the Write-Baton/111111 reason: Failed all paths during body
[info] FAILED! https://writing.com/main/interact/item_id/Pass the Write-Baton/1111111 reason: Failed all paths during body
[info] FAILED! https://writing.com/main/interact/item_id/Pass the Write-Baton/1111121 reason: Failed all paths during body
[info] FAILED! https://writing.com/main/interact/item_id/Pass the Write-Baton/11111111 reason: Failed all paths during body
[info] FAILED! https://writing.com/main/interact/item_id/Pass the Write-Baton/111112 reason: Failed all paths during body
[info] FAILED! https://writing.com/main/interact/item_id/Pass the Write-Baton/11111211 reason: Failed all paths during body
[info] FAILED! https://writing.com/main/interact/item_id/Pass the Write-Baton/111112112 reason: Failed all paths during body
[info] FAILED! https://writing.com/main/interact/item_id/Pass the Write-Baton/1111121122 reason: Failed all paths during body

**Comment by SolRacht** [comment]
That is strange - I am using a Mac, and sadly can't test this on Windows. I'm able to scrape those chapters on my end - I wonder if the HTML of the pages you're fetching is different than expected? The code tries a few different CSS Selectors to find the body content, defined here:
https://github.com/SolRacht/WritingComDownloader/blob/24c15ce6553e4fde9df821cdd7d820549ef9e601/src/main/scala/scraper/scraping/Paths.scala#L16
If you're comfortable doing this, you could try opening one of those chapters in your browser, and seeing if the CSS Selector for the \<div\> containing the chapter content is different from the ones defined there.

If you're going to debug it, I would check that the html in `doc` isn't messed up:
https://github.com/SolRacht/WritingComDownloader/blob/24c15ce6553e4fde9df821cdd7d820549ef9e601/src/main/scala/scraper/scraping/Scraper.scala#L101
