### ISSUE TITLE
Could not determine chapter body

### ISSUE THREAD

**Issue by Lyonesz** [SolRacht/WritingComDownloader#2]
This looks like a handy tool! However, I can't get it to work. I get the same error on any interactive I try to scrape.

FAILED! reason: Could not determine chapter body

Also, I tried running sbt test and only 4 out of the 11 passed. Did Writing.com make a breaking change or could something be wrong in my environment?

Windows 10
JDK 11
SBT 1.3.13
Sqlite 3.33.0

**Comment by SolRacht** [comment]
Hi, this is untested on Windows. For Java, I'm using`openjdk 14.0.2 2020-07-14`.
Are you using cookies from a premium writing.com account?

**Comment by SolRacht** [comment]
You might have more luck with it now that it's using Docker

**Comment by Lyonesz** [comment]
Thanks for the response! I had a paid plan, I think it was the Basic tier. However, any paid plan (even Basic) removes the limit on Interactive viewing. Is there something about the Premium tier that's required? If Basic should work I'll try again if/when I decide to resubscribe.

**Comment by SolRacht** [comment]
Yeah, any paid account will work, as long as you don't get the "Interactive Stories are Temporarily Unavailable" page.
But it looks like the HTML has changed again, and the scraper doesn't work. I'll update soon.

**Comment by SolRacht** [comment]
Should be good now.
